### PR TITLE
Use BindGlobal instead of MakeReadOnlyGlobal

### PR DESCRIPTION
**Pull request by fingolfin**
Note that to safely re-read a file which uses BindGlobal, one may use `Reread` or `RereadPackage`.

### CODE REVIEW

**Comment by Stefan-Kohl** [comment]
Using BindGlobal instead of MakeReadOnlyGlobal is probably a good idea -- but then the initializations of the lists of trial divisors in general.gi need to be removed. Also some care needs to be taken since the variables are then unbound before the corresponding files are read (check for IsBound instead of IsEmpty etc.).

**Comment by fingolfin** [comment]
Not sure what you mean with "the variables are then unbound before the corresponding files are read". Perhaps give an example?

**Comment by Stefan-Kohl** [comment]
Things are simpler to understand from the code than to explain in this case, but anyway:
Look at https://travis-ci.org/gap-packages/FactInt/jobs/330027883 . The failure is due to attempts to use BindGlobal on variables which are already bound. So these variables shouldn't be initialised before BindGlobal is used to assign a value to them. But when they are not initialised, they are unbound before the corresponding files are read. E.g. before tables/factorial.g is read, K_FACTORIAL_M1_FACTORS is unbound then, and you cannot check for IsEmpty, but need to check for IsBoundGlobal instead.

**Comment by fingolfin** [comment]
Ahh, I didn't notice the test failure, my bad. OK, the cleanest solution seems to simply always load those tables; they are tiny by modern standards, no need to delay loading them, or do any other complicated things (such as using `InstallGlobalValue`, or `DeclareAutoreadableVariables`)

**Pull request merged**
